baseURL = "http://idablomquist.dk/kea/typography_theme"
languageCode = "da-DK"
title = "Mit site"
theme = "typography_theme"

[[menu.main]]
    name = "Home"
    title = "home"
    weight = 1
    identifier = "Home"
    url = "/"
     
    [[menu.main]]
    name = "About"
    title = "about"
    weight = 2
    identifier = "About"
    url = "/about"
    
    [[menu.main]]
    name = "guide"
    title = "guide"
    weight = 3
    identifier = "guide"
    url = "/guide/"
    
    [[menu.main]]
    name = "datavisualisering"
    title = "datavisualisering"
    weight = 4
    identifier = "datavisualisering"
    url = "/datavisualisering/"
    
    [[menu.main]]
    name = "Contact"
    title = "contact"
    weight = 5
    identifier = "Contact"
    url = "/contact/"
   