baseURL = "http://idablomquist.dk/kea/mitsite"
languageCode = "en-us"
title = "Mit site"
theme = "systematik"

[[menu.main]]
    name = "Home"
    title = "home section"
    weight = 1
    identifier = "Home"
    url = "/"
    
    [[menu.main]]
    name = "Dokumentation"
    title = "dokumentation section"
    weight = 2
    identifier = "Dokumentation"
    url = "/dokumentation/"
    
    [[menu.main]]
    name = "Om"
    title = "om section"
    weight = 3
    identifier = "Om"
    url = "/om/"